### PR TITLE
Add more checks for partial downloads

### PR DESCRIPTION
**Pull request by weyhan**
* Previous commit [b39dc0c] were only fixes for WWDC 2015 downloads

Current commit fixes for all previous years' downloads.

### CODE REVIEW

**Comment by ohoachuck** [comment]
Thanx you Weyhan for your fix.
Unfortunately Apple have changed the video locations so I have started a new script from crash just for 2016. The all point of this script was to play with scripting more than to have a great solution for downloading videos. Now that Swift is in the air, I get myself into it for the fun also. I'm at WWDC and need to get all videos from this fast connexion, I then just started a Swift version of this script that will so far be very basic, but will do the job for 2016.
Note: I'll not merge your part to not get people confused and believe the script would work for 2016.
Thank you again for your contribution.

**Comment by weyhan** [comment]
Yeah. I did realized Apple's site change that made my contribution useless.

**Comment by ohoachuck** [comment]
I Hope you don't think I'm not grateful for your contribution just because it was useless at the time you did it. I'm always amazed to see such collaborative code approach  that I truly love. I love GitHub for that. It's just magic for me to start something and see people get concerned with bringing their contribution. 
Thanx again for that.

O.


Envoyé de mon iPhone

**Comment by weyhan** [comment]
None at all. I'm glad to have contributed and will do again when I can.

**Pull request closed without merging**
