### PR TITLE
Fix issue where download video is without sound.

### PR DESCRIPTION
**Pull request by weyhan**
This year, Apple has split the audio track into a separate stream, so the audio track has to be downloaded separately.

Unfortunately, with this change, I've not figured how to make `avconvert` to do the same merging of the audio and video track. So, that part is taken out from the script until the time I've found how to get `avconvert` to work the same as ffmpeg.

### CODE REVIEW

**Comment by ohoachuck** [comment]
Thanks !

**Comment by weyhan** [comment]
You're welcome.

**Comment by ohoachuck** [comment]
Have you seen there is a crash when using latest swift version (I believe). It's seems to crash when xcode-select --version give 2363.
The weird part is that this work on Playground but not on terminal. I haven'y yet figured out why.

O.

**Comment by weyhan** [comment]
I've just tested on the latest Xcode and it looks like the swift compiler crash. Xcode 10.1 I was working on has no issue though. Because the swift compiler crashed, I can't figure out what is the root cause. :|

**Comment by weyhan** [comment]
As far as I can tell, it crashes when calling the download functions in DownloadSessionManager. It may be due to code not compatible with the latest Swift but it's also a bug in the compiler that causes it to crash. I think the best way to deal with it is to make a note in the readme that Xcode 10.2.1 is currently not supported?

**Comment by ohoachuck** [comment]
Hum... I'm not sure.
I have the latest Xcode - Version 10.2.1 (10E1001) and it's works for me.
And for some unknown reason, my version of xcode-select doesn't seems to be the same as others.
Mine is 2354. Some others have 2363 (for the same Xcode version - Version 10.2.1).

**Comment by weyhan** [comment]
That is really strange. I’m not at my Mac now so I can’t verify my version. Will check later to confirm. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ohoachuck** [comment]
Better to move the discussion to the related issue here: https://github.com/ohoachuck/wwdc-downloader/issues/87
I found out that while I had the latest Xcode version my mac os wasn't the latest and I'm confuses about who bring update to swift ...
Since I have made the updated on mac os this afternoon: I have now the issue. 
/usr/bin/swift probably used by the script is updated. So it's more probably a swift 5 issue.
I wonder if Xcode the /usr/bin/swift ...

**Pull request merged**
